#!/usr/bin/env bash

nFiles=$(find |  grep ff | wc -l)
files=$(find | grep ff)

for ((n=1;n<=$nFiles;n++))

do

path=$(find | grep ff | head -$n | tail -1 | cut -d"/" -f2-5)
pathDate=$(find | grep ff | head -$n | tail -1 | cut -d"/" -f2-4 | tr "/" "-")
fileDate=$(cat $path | head -1)
fileName=$(find | grep ff | head -$n | tail -1 | cut -d"/" -f5) #to determine how files are corrupted compared to the original dataset 
wholePath=$(find | grep ff | head =$n | tail -1)

        if [[ "$pathDate" != "$fileDate" ]]
        then
                echo $fileName "is corrupted"

        fi
done
